### ISSUE TITLE
Could you provide the code for the link prediction task?

### ISSUE THREAD

**Issue by 1didi** [MrYaoH/GRCCA#1]
Could you provide the code for the link prediction task? The link prediction results I implemented differ significantly from those in the paper, but I don't know where the problem lies.I would be very grateful if I could receive your help.

**Comment by MrYaoH** [comment]
Thank you for your interest in our work. We have uploaded new files w.r.t. link prediction tasks and updated the 'test.py' file about metrics: AUC and AP. Additionally, we have uploaded the splited data at https://drive.google.com/drive/folders/1Kz59BmtgFxRfRWNhmRH4nSTgv5qWnWEm used in our experiments.
